pipeline:
  setup:
    image: node:10
    when:
      event: push
    commands:
      - yarn
  lint:
    image: node:10
    when:
      event: push
    group: testing
    commands:
      - yarn lint
  build:
    image: node:10
    when:
      event: push
      branch:
        exclude: [ master ]
    group: testing
    commands:
      - yarn build
  docker:
    image: plugins/docker
    when:
      branch:
        - master
      event: push
      status: success
    registry: https://registry.webkom.dev
    repo: registry.webkom.dev/webkom/office-dashboard
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
      - latest
    build_args:
      - RELEASE=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}

