---
kind: pipeline
type: docker
name: defult

steps:
  - name: setup
    image: node:12
    when:
      event: push
    commands:
      - yarn

  - name: lint
    image: node:12
    when:
      event: push
    depends_on: [setup]
    commands:
      - yarn lint

  - name: build
    image: node:12
    when:
      event: push
      branch:
        exclude: [master]
    depends_on: [setup]
    commands:
      - yarn build

  - name: docker
    image: plugins/docker
    when:
      branch:
        - master
      event: push
      status: success
    settings:
      registry: https://registry.webkom.dev
      repo: registry.webkom.dev/webkom/office-dashboard
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
        - latest
      build_args:
        - RELEASE=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
