---
kind: pipeline
type: docker
name: default

steps:
  - name: setup
    image: node:22-alpine
    when:
      event: [push]
    commands:
      - yarn

  - name: lint
    image: node:22-alpine
    when:
      event: [push]
    depends_on: [setup]
    commands:
      - yarn lint

  - name: build
    image: node:22-alpine
    when:
      event: [push]
      branch:
        exclude: [master]
    depends_on: [setup]
    commands:
      - yarn build

  - name: docker-frontend
    image: plugins/docker
    when:
      branch:
        - master
      event: [push]
      status: [success]
    settings:
      registry: https://registry.webkom.dev
      repo: registry.webkom.dev/webkom/office-dashboard
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
        - latest
      build_args:
        - RELEASE=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}

  - name: docker-backend
    image: plugins/docker
    when:
      branch:
        - master
      event: [push]
      status: [success]
    settings:
      registry: https://registry.webkom.dev
      dockerfile: office-dashboard-backend/Dockerfile
      context: office-dashboard-backend
      repo: registry.webkom.dev/webkom/office-dashboard-backend
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
        - latest
      build_args:
        - RELEASE=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}

  - name: Deploy
    image: abakus/ansible-deploy
    when:
      branch:
        - master
      event: [push]
      status: [success]
    settings:
      playbook: /infrastructure/office/playbooks/deploy.yml
      repository:
        from_secret: infra_repository
      tags:
        - dashboard
      inventory: /infrastructure/inventory
      vault_password:
        from_secret: ansible_vault_password
      private_key:
        from_secret: infra_deploy_key
    depends_on:
      - docker-frontend
      - docker-backend

---
kind: signature
hmac: cdfcd18914d68aa47548b2db59cda69a51bc960902a68d732d5bd3e211ce31c4
